apiVersion: v1
kind: Service
metadata:
  name: backend-node
spec:
  selector:
    app: second-app
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app-deployment
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: second-app
  template: 
    metadata: 
      labels:
        app: second-app 
    spec:
      containers:
        - name: second-nodejs
          image: pomdockercpe/kube-first-app:2 