apiVersion: v1
kind: Service
metadata:
  name: backend-node
spec:
  selector:
    #เก่าเลยไม่ต้องใา่ matchLabels
    app: second-app
    #สามารถ ใส่แค่ keypair อันเดียว pod ทุกตัวถ้ามี key pair นี้เจอกันเลย
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 8080
    #- protocol: 'TCP'
      #port: 443
      #targetPort: 443
  #type: ClusterIP
  #type: NodePort
  type: LoadBalancer